In [16]:
import pandas as pd
from sklearn.preprocessing import Imputer
%matplotlib inline

In [76]:
train_df = pd.read_csv('../dat/train.csv')
print(train_df.shape)
train_df.head(3)

(1460, 81)


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  

[3 rows x 81 columns]

In [50]:
train_df.dtypes


Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley             object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
                  ...   
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
FireplaceQu       object
GarageType        object
GarageYrBlt      float64


In [6]:

print(len(train_df.columns))
train_df.columns

81


Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

# Missing values

In [ ]:
train_df.isnull() # Gives True/False df for the entries that are null

In [15]:
print(train_df.isnull().sum())
null_stats = train_df.isnull().sum()
#type(null_stats)# Series
null_stats.nonzero() # Indixes of non-zeros, so the entries that have null

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley               0
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
                 ... 
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive

(array([ 3, 25, 26, 30, 31, 32, 33, 35, 42, 57, 58, 59, 60, 63, 64, 72, 73,
        74], dtype=int64),)

In [23]:
non_zeros_indices = null_stats.nonzero()
print(type(non_zeros_indices))

missing_val_cols = null_stats[non_zeros_indices[0]]# Here are the colomns that have nulls
#null_stats[non_zeros_indices[0]].hist()
print(missing_val_cols.index)

<class 'tuple'>
Index(['LotFrontage', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical',
       'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature'],
      dtype='object')


## Fit imputer 

In [46]:
data_imputer = Imputer()
train_df = data_imputer.fit_transform(train_df)# Does not work for string vals

ValueError: could not convert string to float: 'Normal'

In [31]:
missing_cols_types = train_df.dtypes[missing_val_cols.index] # Ex: Alley is object
# We need to fill in some strings in the object missing vals
print(missing_cols_types[missing_cols_types==object])# These are the cols of type object
print(missing_cols_types[missing_cols_types!=object])

MasVnrType      object
BsmtQual        object
BsmtCond        object
BsmtExposure    object
BsmtFinType1    object
BsmtFinType2    object
Electrical      object
FireplaceQu     object
GarageType      object
GarageFinish    object
GarageQual      object
GarageCond      object
PoolQC          object
Fence           object
MiscFeature     object
dtype: object
LotFrontage    float64
MasVnrArea     float64
GarageYrBlt    float64
dtype: object


# Cleaner way to fill object type (string) missing vals:

In [35]:
# Let's fill the object types cols with "None"
object_type_missing_vals_col = missing_cols_types[missing_cols_types==object].index
train_df[object_type_missing_vals_col] = train_df[object_type_missing_vals_col].fillna("None")

In [7]:
#train_df['Alley'] = train_df['Alley'].dropna()
#train_df['Alley'] = train_df['Alley'].fillna('None')

In [55]:
# Now check if there are any missings vals left of type object
train_df[train_df.isnull().sum().nonzero()[0]].dtypes

LotFrontage    float64
MasVnrArea     float64
GarageYrBlt    float64
dtype: object

In [46]:
# Now we can fit an imputer
data_imputer = Imputer()
train_df = data_imputer.fit_transform(train_df)# Still gets an error since even if cols are not null they are still strings



ValueError: could not convert string to float: 'Normal'

In [66]:
cols_to_impute = train_df[train_df.isnull().sum().nonzero()[0]].dtypes.index
train_df[cols_to_impute].head(3)

LotFrontage  MasVnrArea  GarageYrBlt
0         65.0       196.0       2003.0
1         80.0         0.0       1976.0
2         68.0       162.0       2001.0

In [64]:
# We need to fit the imputer only to the non-object cols
data_imputer = Imputer()
new_train_df = data_imputer.fit_transform(train_df[cols_to_impute])
print(new_train_df)# not a df
print(type(new_train_df))# numpy array!


[[   65.   196.  2003.]
 [   80.     0.  1976.]
 [   68.   162.  2001.]
 ..., 
 [   66.     0.  1941.]
 [   68.     0.  1950.]
 [   75.     0.  1965.]]
<class 'numpy.ndarray'>


# Cleaner way to impute only non-object vals

In [75]:
train_df_non_obj = train_df.select_dtypes(exclude=['object'])
print(train_df_non_obj.dtypes)
print(train_df_non_obj.shape)
new_train_df = data_imputer.fit_transform(train_df_non_obj)
type(new_train_df)# Still numpy array!!

Id                 int64
MSSubClass         int64
LotFrontage      float64
LotArea            int64
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
MasVnrArea       float64
BsmtFinSF1         int64
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath       int64
BsmtHalfBath       int64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
TotRmsAbvGrd       int64
Fireplaces         int64
GarageYrBlt      float64
GarageCars         int64
GarageArea         int64
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
MiscVal            int64
MoSold             int64
YrSold             int64
SalePrice          int64
dtype: object
(1460, 38)


numpy.ndarray

In [78]:
# convert into a df
new_train_df = pd.DataFrame(new_train_df, index=train_df_non_obj.index, columns=train_df_non_obj.columns)
print(new_train_df.shape)
print(new_train_df.head(3))

(1460, 38)
    Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0  1.0        60.0         65.0   8450.0          7.0          5.0     2003.0   
1  2.0        20.0         80.0   9600.0          6.0          8.0     1976.0   
2  3.0        60.0         68.0  11250.0          7.0          5.0     2001.0   

   YearRemodAdd  MasVnrArea  BsmtFinSF1    ...      WoodDeckSF  OpenPorchSF  \
0        2003.0       196.0       706.0    ...             0.0         61.0   
1        1976.0         0.0       978.0    ...           298.0          0.0   
2        2002.0       162.0       486.0    ...             0.0         42.0   

   EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  \
0            0.0        0.0          0.0       0.0      0.0     2.0  2008.0   
1            0.0        0.0          0.0       0.0      0.0     5.0  2007.0   
2            0.0        0.0          0.0       0.0      0.0     9.0  2008.0   

   SalePrice  
0   208500.0  


In [86]:
# Now check for any Nan in the new df
print(new_train_df.isnull().sum())
print(new_train_df.isnull().sum().nonzero())
print('Number of null entries is: ', len(new_train_df.isnull().sum().nonzero()[0]))

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64
(array([], dtype=int64),)
Number of null entries is:  0


# Putting it all together

In [110]:
train_df = pd.read_csv('../dat/train.csv')
print(train_df.shape)
train_df.head(3)

(1460, 81)


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  

[3 rows x 81 columns]

In [91]:
# Number of colomns with nulls
def check_nulls(df):
    return len(df.isnull().sum().nonzero()[0])

In [93]:
print('Number of colomns with nulls: ', check_nulls(train_df))

Number of colomns with nulls:  19


## Object type fill in missing vals:

In [111]:
train_df_obj = train_df.select_dtypes(include=['object'])
print(train_df_obj.shape)
train_df_obj.dtypes

(1460, 43)


MSZoning         object
Street           object
Alley            object
LotShape         object
LandContour      object
Utilities        object
LotConfig        object
LandSlope        object
Neighborhood     object
Condition1       object
Condition2       object
BldgType         object
HouseStyle       object
RoofStyle        object
RoofMatl         object
Exterior1st      object
Exterior2nd      object
MasVnrType       object
ExterQual        object
ExterCond        object
Foundation       object
BsmtQual         object
BsmtCond         object
BsmtExposure     object
BsmtFinType1     object
BsmtFinType2     object
Heating          object
HeatingQC        object
CentralAir       object
Electrical       object
KitchenQual      object
Functional       object
FireplaceQu      object
GarageType       object
GarageFinish     object
GarageQual       object
GarageCond       object
PavedDrive       object
PoolQC           object
Fence            object
MiscFeature      object
SaleType        

In [117]:
print('Number of colomns with nulls: ', check_nulls(train_df_obj))

Number of colomns with nulls:  0


In [115]:
train_df_obj = train_df_obj.fillna("None")

In [116]:
print('Number of colomns with nulls: ', check_nulls(train_df_obj))

Number of colomns with nulls:  0


## Numerical missing values handling:

In [118]:
imp = Imputer()
train_df_non_obj = train_df.select_dtypes(exclude=['object'])
print(train_df_non_obj.shape)

(1460, 38)


In [119]:
print('Number of colomns with nulls: ', check_nulls(train_df_non_obj))

Number of colomns with nulls:  3


In [120]:
#train_df_non_obj = imp.fit_transform(train_df_non_obj)
train_df_non_obj = pd.DataFrame(imp.fit_transform(train_df_non_obj), index=train_df_non_obj.index, columns=train_df_non_obj.columns)
print(train_df_non_obj.head(3))

    Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0  1.0        60.0         65.0   8450.0          7.0          5.0     2003.0   
1  2.0        20.0         80.0   9600.0          6.0          8.0     1976.0   
2  3.0        60.0         68.0  11250.0          7.0          5.0     2001.0   

   YearRemodAdd  MasVnrArea  BsmtFinSF1    ...      WoodDeckSF  OpenPorchSF  \
0        2003.0       196.0       706.0    ...             0.0         61.0   
1        1976.0         0.0       978.0    ...           298.0          0.0   
2        2002.0       162.0       486.0    ...             0.0         42.0   

   EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  \
0            0.0        0.0          0.0       0.0      0.0     2.0  2008.0   
1            0.0        0.0          0.0       0.0      0.0     5.0  2007.0   
2            0.0        0.0          0.0       0.0      0.0     9.0  2008.0   

   SalePrice  
0   208500.0  
1   181500.

In [121]:
print('Number of colomns with nulls: ', check_nulls(train_df_non_obj))

Number of colomns with nulls:  0


## Now put the two transfroms together

In [124]:
train_df = pd.concat([train_df_non_obj, train_df_obj], axis=1)

In [125]:
train_df.shape

(1460, 81)

In [127]:
train_df.head(3)

Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0  1.0        60.0         65.0   8450.0          7.0          5.0     2003.0   
1  2.0        20.0         80.0   9600.0          6.0          8.0     1976.0   
2  3.0        60.0         68.0  11250.0          7.0          5.0     2001.0   

   YearRemodAdd  MasVnrArea  BsmtFinSF1      ...        GarageType  \
0        2003.0       196.0       706.0      ...            Attchd   
1        1976.0         0.0       978.0      ...            Attchd   
2        2002.0       162.0       486.0      ...            Attchd   

   GarageFinish  GarageQual  GarageCond  PavedDrive  PoolQC  Fence  \
0           RFn          TA          TA           Y    None   None   
1           RFn          TA          TA           Y    None   None   
2           RFn          TA          TA           Y    None   None   

   MiscFeature  SaleType  SaleCondition  
0         None        WD         Normal  
1         None        WD         Normal  
2         None        WD         Normal  

[3 rows x 81 columns]

In [126]:
print('Number of colomns with nulls: ', check_nulls(train_df))

Number of colomns with nulls:  0
